python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 4 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 0 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 1 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 2 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 3 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 4 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Hero_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Hero_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Hero_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Hero_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 4 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Hero_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 0 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Hero_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 1 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Hero_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 2 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Hero_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 3 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Hero_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 4 --manual_name Hero --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Hero_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 4 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 0 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 1 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 2 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 3 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 4 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path MontezumaRevenge_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path MontezumaRevenge_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path MontezumaRevenge_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path MontezumaRevenge_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 4 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path MontezumaRevenge_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 0 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path MontezumaRevenge_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 1 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path MontezumaRevenge_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 2 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path MontezumaRevenge_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 3 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path MontezumaRevenge_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 4 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path MontezumaRevenge_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 4 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 0 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 1 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 2 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 3 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 4 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Pitfall_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Pitfall_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Pitfall_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Pitfall_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 4 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Pitfall_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 0 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Pitfall_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 1 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Pitfall_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 2 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Pitfall_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 3 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Pitfall_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 4 --manual_name Pitfall --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Pitfall_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 4 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 0 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 1 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 2 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 3 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 4 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Qbert_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Qbert_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Qbert_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Qbert_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 4 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Qbert_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 0 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Qbert_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 1 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Qbert_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 2 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Qbert_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 3 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Qbert_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 4 --manual_name Qbert --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Qbert_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 4 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 0 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 1 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 2 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 3 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 4 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Riverraid_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Riverraid_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Riverraid_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Riverraid_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 4 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Riverraid_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 0 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Riverraid_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 1 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Riverraid_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 2 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Riverraid_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 3 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Riverraid_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 4 --manual_name Riverraid --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path Riverraid_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 4 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 0 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 1 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 2 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 3 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 4 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path SpaceInvaders_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path SpaceInvaders_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path SpaceInvaders_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path SpaceInvaders_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 4 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path SpaceInvaders_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 0 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path SpaceInvaders_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 1 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path SpaceInvaders_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 2 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path SpaceInvaders_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 3 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path SpaceInvaders_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 4 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 4 --api_type llama --traj_path SpaceInvaders_language_traj_0929.pkl --distiller traj_distiller
