python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 4 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 0 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 1 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 2 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 3 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 4 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Breakout_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Breakout_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Breakout_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Breakout_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 4 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Breakout_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 0 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Breakout_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 1 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Breakout_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 2 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Breakout_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 3 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Breakout_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 4 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Breakout_language_traj_0929.pkl --distiller traj_distiller
