python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 4 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 0 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 1 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 2 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 3 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 4 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Qbert_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Qbert_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Qbert_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Qbert_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 4 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Qbert_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 0 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Qbert_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 1 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Qbert_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 2 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Qbert_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 3 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Qbert_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 4 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Qbert_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 4 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 0 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 1 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 2 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 3 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 4 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 4 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 0 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 1 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 2 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 3 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedQbert-v0 --init_summarizer RepresentedQbert_init_translator --curr_summarizer RepresentedQbert_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 4 --manual_name Qbert --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 4 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 0 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 1 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 2 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 3 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 4 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Riverraid_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Riverraid_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Riverraid_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Riverraid_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 4 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Riverraid_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 0 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Riverraid_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 1 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Riverraid_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 2 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Riverraid_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 3 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Riverraid_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 4 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Riverraid_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 4 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 0 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 1 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 2 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 3 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 4 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 4 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 0 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 1 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 2 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 3 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedRiverraid-v0 --init_summarizer RepresentedRiverraid_init_translator --curr_summarizer RepresentedRiverraid_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 4 --manual_name Riverraid --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 4 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 0 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 1 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 2 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 3 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 4 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Seaquest_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Seaquest_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Seaquest_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Seaquest_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 4 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Seaquest_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 0 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Seaquest_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 1 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Seaquest_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 2 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Seaquest_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 3 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Seaquest_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 4 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Seaquest_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 4 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 0 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 1 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 2 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 3 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 4 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 4 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 0 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 1 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 2 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 3 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSeaquest-v0 --init_summarizer RepresentedSeaquest_init_translator --curr_summarizer RepresentedSeaquest_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 4 --manual_name Seaquest --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
