python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 4 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 0 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 1 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 2 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 3 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 4 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 4 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 0 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 1 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 2 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 3 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 4 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
