python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 0 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 1 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 2 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 3 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 0 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 1 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 2 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 3 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path DemonAttack_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path DemonAttack_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path DemonAttack_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path DemonAttack_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 0 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path DemonAttack_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 1 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path DemonAttack_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 2 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path DemonAttack_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 3 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path DemonAttack_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 0 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 1 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 2 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedDemonAttack-v0 --init_summarizer RepresentedDemonAttack_init_translator --curr_summarizer RepresentedDemonAttack_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 3 --manual_name DemonAttack --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 0 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 1 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 2 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 3 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 0 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 1 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 2 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 3 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Freeway_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Freeway_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Freeway_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Freeway_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 0 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Freeway_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 1 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Freeway_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 2 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Freeway_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 3 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Freeway_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 0 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 1 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 2 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFreeway-v0 --init_summarizer RepresentedFreeway_init_translator --curr_summarizer RepresentedFreeway_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 3 --manual_name Freeway --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 0 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 1 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 2 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 3 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 0 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 1 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 2 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 3 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Frostbite_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Frostbite_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Frostbite_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Frostbite_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 0 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Frostbite_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 1 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Frostbite_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 2 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Frostbite_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 3 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Frostbite_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 0 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 1 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 2 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedFrostbite-v0 --init_summarizer RepresentedFrostbite_init_translator --curr_summarizer RepresentedFrostbite_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 3 --manual_name Frostbite --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
