python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 0 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 1 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 2 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 3 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 0 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 1 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 2 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 3 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Pitfall_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Pitfall_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Pitfall_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Pitfall_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 0 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Pitfall_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 1 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Pitfall_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 2 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Pitfall_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 3 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Pitfall_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 0 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 1 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 2 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPitfall-v0 --init_summarizer RepresentedPitfall_init_translator --curr_summarizer RepresentedPitfall_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 3 --manual_name Pitfall --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 0 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 1 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 2 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 3 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 0 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 1 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 2 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 3 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Pong_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Pong_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Pong_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Pong_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 0 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Pong_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 1 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Pong_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 2 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Pong_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 3 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Pong_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 0 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 1 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 2 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPong-v0 --init_summarizer RepresentedPong_init_translator --curr_summarizer RepresentedPong_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 3 --manual_name Pong --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 0 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 1 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 2 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 3 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 0 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 1 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 2 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 3 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path PrivateEye_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path PrivateEye_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path PrivateEye_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path PrivateEye_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 0 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path PrivateEye_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 1 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path PrivateEye_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 2 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path PrivateEye_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 3 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path PrivateEye_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 0 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 1 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 2 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedPrivateEye-v0 --init_summarizer RepresentedPrivateEye_init_translator --curr_summarizer RepresentedPrivateEye_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 3 --manual_name PrivateEye --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
