python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 0 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 1 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 2 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 3 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 0 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 1 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 2 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 3 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Hero_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Hero_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Hero_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Hero_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 0 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Hero_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 1 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Hero_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 2 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Hero_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 3 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path Hero_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 0 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 1 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 2 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedHero-v0 --init_summarizer RepresentedHero_init_translator --curr_summarizer RepresentedHero_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 3 --manual_name Hero --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 0 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 1 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 2 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 3 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 0 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 1 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 2 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 3 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path MontezumaRevenge_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path MontezumaRevenge_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path MontezumaRevenge_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path MontezumaRevenge_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 0 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path MontezumaRevenge_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 1 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path MontezumaRevenge_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 2 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path MontezumaRevenge_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 3 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path MontezumaRevenge_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 0 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 1 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 2 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMontezumaRevenge-v0 --init_summarizer RepresentedMontezumaRevenge_init_translator --curr_summarizer RepresentedMontezumaRevenge_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 3 --manual_name MontezumaRevenge --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 0 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 1 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 2 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 3 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 0 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 1 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 2 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 3 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path MsPacman_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path MsPacman_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path MsPacman_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path MsPacman_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 0 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path MsPacman_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 1 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path MsPacman_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 2 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path MsPacman_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 3 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --traj_path MsPacman_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 0 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 1 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 2 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
python main_reflexion.py --env_name RepresentedMsPacman-v0 --init_summarizer RepresentedMsPacman_init_translator --curr_summarizer RepresentedMsPacman_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 3 --manual_name MsPacman --use_short_mem 0 --max_episode_len 1000 --api_type qwen7b --distiller traj_distiller
