python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 0 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 1 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 2 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 3 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 0 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 1 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 2 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 3 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Venture_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Venture_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Venture_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Venture_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 0 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Venture_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 1 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Venture_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 2 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Venture_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 3 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Venture_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 0 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 1 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 2 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVenture-v0 --init_summarizer RepresentedVenture_init_translator --curr_summarizer RepresentedVenture_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 3 --manual_name Venture --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 0 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 1 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 2 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 3 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 0 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 1 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 2 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 3 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path VideoPinball_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path VideoPinball_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path VideoPinball_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path VideoPinball_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 0 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path VideoPinball_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 1 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path VideoPinball_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 2 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path VideoPinball_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 3 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path VideoPinball_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 0 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 1 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 2 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedVideoPinball-v0 --init_summarizer RepresentedVideoPinball_init_translator --curr_summarizer RepresentedVideoPinball_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 3 --manual_name VideoPinball --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
