python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 4 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 0 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 1 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 2 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 3 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 4 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 4 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 0 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 1 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 2 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 3 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 4 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
