python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 0 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 1 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 2 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 3 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 0 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 1 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 2 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 3 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Skiing_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Skiing_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Skiing_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Skiing_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 0 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Skiing_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 1 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Skiing_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 2 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Skiing_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 3 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Skiing_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 0 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 1 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 2 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSkiing-v0 --init_summarizer RepresentedSkiing_init_translator --curr_summarizer RepresentedSkiing_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 3 --manual_name Skiing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 0 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 1 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 2 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 3 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 0 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 1 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 2 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 3 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path SpaceInvaders_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path SpaceInvaders_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path SpaceInvaders_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path SpaceInvaders_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 0 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path SpaceInvaders_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 1 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path SpaceInvaders_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 2 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path SpaceInvaders_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 3 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path SpaceInvaders_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 0 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 1 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 2 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedSpaceInvaders-v0 --init_summarizer RepresentedSpaceInvaders_init_translator --curr_summarizer RepresentedSpaceInvaders_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 3 --manual_name SpaceInvaders --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 0 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 1 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 2 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider cot_actor --prompt_level 1 --num_trails 3 --seed 3 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 0 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 1 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 2 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider cot_actor --prompt_level 6 --num_trails 3 --seed 3 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Tennis_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Tennis_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Tennis_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Tennis_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 0 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Tennis_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 1 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Tennis_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 2 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Tennis_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider cot_actor --prompt_level 7 --num_trails 3 --seed 3 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Tennis_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 0 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 1 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 2 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedTennis-v0 --init_summarizer RepresentedTennis_init_translator --curr_summarizer RepresentedTennis_basic_translator --decider cot_actor --prompt_level 8 --num_trails 3 --seed 3 --manual_name Tennis --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
