python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 0 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 1 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 2 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 3 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 0 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 1 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 2 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 3 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Bowling_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Bowling_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Bowling_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Bowling_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 0 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Bowling_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 1 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Bowling_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 2 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Bowling_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 3 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Bowling_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 0 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 1 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 2 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBowling-v0 --init_summarizer RepresentedBowling_init_translator --curr_summarizer RepresentedBowling_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 3 --manual_name Bowling --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 0 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 1 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 2 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 3 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 0 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 1 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 2 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 3 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Boxing_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Boxing_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Boxing_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Boxing_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 0 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Boxing_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 1 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Boxing_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 2 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Boxing_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 3 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Boxing_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 0 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 1 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 2 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBoxing-v0 --init_summarizer RepresentedBoxing_init_translator --curr_summarizer RepresentedBoxing_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 3 --manual_name Boxing --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 0 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 1 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 2 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 1 --num_trails 1 --seed 3 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 0 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 1 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 2 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 1 --num_trails 5 --seed 3 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 0 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 1 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 2 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 6 --num_trails 1 --seed 3 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 0 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 1 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 2 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 6 --num_trails 5 --seed 3 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 0 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Breakout_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 1 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Breakout_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 2 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Breakout_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 7 --num_trails 1 --seed 3 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Breakout_language_traj_0929.pkl
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 0 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Breakout_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 1 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Breakout_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 2 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Breakout_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 7 --num_trails 5 --seed 3 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --traj_path Breakout_language_traj_0929.pkl --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 0 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 1 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 2 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider naive_actor --prompt_level 8 --num_trails 1 --seed 3 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 0 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 1 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 2 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
python main_reflexion.py --env_name RepresentedBreakout-v0 --init_summarizer RepresentedBreakout_init_translator --curr_summarizer RepresentedBreakout_basic_translator --decider cot_actor --prompt_level 8 --num_trails 5 --seed 3 --manual_name Breakout --use_short_mem 0 --max_episode_len 1000 --api_type llama --distiller traj_distiller
